# Generated by Django 3.0.2 on 2020-02-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
