# Generated by Django 3.0.2 on 2020-02-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Cancha')),
                ('jugador', models.ManyToManyField(to='jobs.Jugador')),
            ],
        ),
    ]
