# Generated by Django 3.0.2 on 2020-02-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200214_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='password',
        ),
    ]
